# So my approach here is that I think of 'script' as the things being
# actually *my* responsibilty.
language: haskell
install:
  - cabal install --only-dependencies
  - sudo apt-get install texlive-latex-base texlive-latex-extra texlive-latex-recommended
  - sudo apt-get install texlive-bibtex-extra
  - sudo apt-get install gnuplot
  - sudo apt-get install coreutils
before_script:
  - git submodule update --init # The "external/" folder
script:
  - ghc --make site.hs
  - ./site build
